services:
  postgres:
    image: postgres:16
    env_file: .env
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./.local/aws:/home/airflow/.aws:ro
    command: ["airflow", "db", "migrate"]
    restart: "no"

  airflow-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    env_file: .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./.local/aws:/home/airflow/.aws:ro
    ports:
      - "8080:8080"
    command: api-server

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
      airflow-dag-processor:
        condition: service_started
    env_file: .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./.local/aws:/home/airflow/.aws:ro
    command: scheduler
  
  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
      airflow-init:
        condition: service_completed_successfully
    env_file: .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: dag-processor

volumes:
  postgres-db-volume: