services:
  - type: web
    name: github-batch-analytics-dashboard
    runtime: python
    plan: free
    buildCommand: pip install uv && uv sync --frozen --no-dev
    startCommand: uv run python -m streamlit run dashboards/app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
      - key: AWS_DEFAULT_REGION
        value: eu-central-1
      - key: ATHENA_DATABASE_NAME
        value: github_analytics
      - key: ATHENA_WORKGROUP_NAME
        value: github-batch-analytics
      - key: ATHENA_REPOSITORY_SUMMARY_TABLE_NAME
        value: repository_dashboard_summary
      - key: ATHENA_QUERY_RESULTS_BUCKET_NAME
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
