apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-batch-analytics.fullname" . }}-airflow-scheduler
  labels:
    {{- include "github-batch-analytics.labels" . | nindent 4 }}
spec:
  replicas: 1
  progressDeadlineSeconds: 900
  strategy:
    type: Recreate
    rollingUpdate: null
  selector:
    matchLabels:
      app.kubernetes.io/component: airflow-scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "github-batch-analytics.labels" . | nindent 8 }}
        app.kubernetes.io/component: airflow-scheduler
    spec:
      terminationGracePeriodSeconds: 180
      serviceAccountName: {{ include "github-batch-analytics.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: airflow-scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-lc", "exec airflow scheduler"]
          envFrom:
            - configMapRef:
                name: {{ include "github-batch-analytics.fullname" . }}-env
            - secretRef:
                name: {{ include "github-batch-analytics.fullname" . }}-secrets
          env:
            - name: AIRFLOW_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: dlt-config
              mountPath: /home/airflow/.dlt/config.toml
              subPath: config.toml
            - name: dlt-secrets
              mountPath: /home/airflow/.dlt/secrets.toml
              subPath: secrets.toml
            - name: dlt-pipelines
              mountPath: /tmp/dlt
          resources:
            {{- toYaml .Values.airflow.resources.scheduler | nindent 12 }}
      volumes:
        - name: dlt-config
          configMap:
            name: {{ include "github-batch-analytics.fullname" . }}-dlt-config
        - name: dlt-secrets
          secret:
            secretName: {{ include "github-batch-analytics.fullname" . }}-dlt-secrets
        - name: dlt-pipelines
          emptyDir: {}
