apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-batch-analytics.fullname" . }}-secrets
  labels:
    {{- include "github-batch-analytics.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: {{ printf "postgresql+psycopg2://%s:%s@%s:%v/%s" .Values.airflow.database.username .Values.airflow.database.password .Values.airflow.database.host .Values.airflow.database.port .Values.airflow.database.name | quote }}
  AIRFLOW__API_AUTH__JWT_SECRET: {{ .Values.airflow.secrets.apiJwtSecret | quote }}
  AIRFLOW__CORE__INTERNAL_API_SECRET_KEY: {{ .Values.airflow.secrets.internalApiSecretKey | quote }}
  AIRFLOW__API__SECRET_KEY: {{ .Values.airflow.secrets.apiSecretKey | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "github-batch-analytics.fullname" . }}-dlt-config
  labels:
    {{- include "github-batch-analytics.labels" . | nindent 4 }}
data:
  config.toml: |
    [destination.filesystem]
    bucket_url = "s3://{{ .Values.airflow.buckets.bronzeZone }}"
    layout = "{table_name}/dt={dt}/hr={hr}/{load_id}.{file_id}.{ext}"

    [destination.filesystem.extra_placeholders]
    dt = "1970-01-01"
    hr = "0"

    [pipeline]
    loader_file_format = "parquet"

    [runtime]
    dlthub_telemetry = false
    enable_runtime_trace = false
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-batch-analytics.fullname" . }}-dlt-secrets
  labels:
    {{- include "github-batch-analytics.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.toml: |
    [sources.github_enrichment]
    github_token = {{ .Values.airflow.dlt.githubToken | quote }}
