apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-batch-analytics.fullname" . }}-spark-worker
  labels:
    {{- include "github-batch-analytics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.spark.worker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: spark-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "github-batch-analytics.labels" . | nindent 8 }}
        app.kubernetes.io/component: spark-worker
    spec:
      serviceAccountName: {{ include "github-batch-analytics.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: spark-worker
          image: "{{ .Values.spark.worker.image.repository }}:{{ .Values.spark.worker.image.tag }}"
          imagePullPolicy: {{ .Values.spark.worker.image.pullPolicy }}
          command:
            - /bin/bash
            - -lc
            - exec /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://{{ include "github-batch-analytics.fullname" . }}-spark-master:7077
          env:
            - name: SPARK_WORKER_DIR
              value: {{ .Values.spark.worker.workDir | quote }}
            - name: SPARK_LOCAL_DIRS
              value: {{ .Values.spark.worker.workDir | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "github-batch-analytics.fullname" . }}-env
            - secretRef:
                name: {{ include "github-batch-analytics.fullname" . }}-secrets
          volumeMounts:
            - name: spark-work-dir
              mountPath: {{ .Values.spark.worker.workDir | quote }}
          resources:
            {{- toYaml .Values.spark.worker.resources | nindent 12 }}
      volumes:
        - name: spark-work-dir
          emptyDir:
            sizeLimit: {{ .Values.spark.worker.workDirSizeLimit }}
