AWS_REGION = "eu-central-1"
AWS_ACCESS_KEY_ID = "<AWS_ACCESS_KEY_ID>"
AWS_SECRET_ACCESS_KEY = "<AWS_SECRET_ACCESS_KEY>"
ATHENA_DATABASE_NAME = "<ATHENA_DATABASE_NAME>"
ATHENA_WORKGROUP_NAME = "<ATHENA_WORKGROUP_NAME>"
ATHENA_QUERY_RESULTS_BUCKET_NAME = "<ATHENA_QUERY_RESULTS_BUCKET_NAME>"
ATHENA_REPOSITORY_SUMMARY_TABLE_NAME = "<ATHENA_REPOSITORY_SUMMARY_TABLE_NAME>"
